version: '3.8'
#plaholder version of docker composer, to update later...
services:
  auction-frontend:
    hostname: auction-frontend
    stdin_open: true
    tty: true
    image: node:current-alpine
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0 << N"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    depends_on:
      - auction-redisdb
      - auction-mongodb
    networks:
      - app-network

  auction-backend:
    hostname: auction-backend
    stdin_open: true
    tty: true
    image: node:current-alpine
    working_dir: /app
    command: sh -c "npm i && npm run build && npm run start"
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - auction-redisdb
      - auction-mongodb
    networks:
      - app-network

  auction-redisdb:
    hostname: auction-redisdb
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  auction-mongodb:
    hostname: auction-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=auction
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
